// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL1ell_ciF6Rdu5FGuUdqOKh-QPaw8mCs',
    appId: '1:801641693646:android:6e8be535ae7e097f316b9f',
    messagingSenderId: '801641693646',
    projectId: 'doclink-d30a3',
    storageBucket: 'doclink-d30a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBycLeC-azO-wGAGUP7nm299JcSz3RpeRk',
    appId: '1:801641693646:ios:d53e7f020f509e75316b9f',
    messagingSenderId: '801641693646',
    projectId: 'doclink-d30a3',
    storageBucket: 'doclink-d30a3.appspot.com',
    androidClientId: '801641693646-625a69ode5q2um4bs7pk2471tson6tll.apps.googleusercontent.com',
    iosClientId: '801641693646-p0j26ap7eakq65tr92ute33kd4ap0n6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.doclink3',
  );
}
